### ISSUE TITLE
MemberController에서 회원 등록 api의 return 값 코드 반복 이슈

### ISSUE THREAD

**Issue by seung-woo-ryu** [Kreamish/KreamishServer#24]
MemberController에서 회원 등록 api의 return 부분에서 코드 반복이 생겨나는 것 같습니다.
아래의 1번 코드의 경우 getBody()를 호출함으로써 2번과 동일해집니다.

[git code link](https://github.com/Kreamish/KreamishServer/blob/808ea513324e4250ed20d84fae02930b6e722679/src/main/java/com/kreamish/kream/member/controller/MemberController.java#L53C5-L53C5)

##### 1번
`ResponseEntity.created(URI.create("/members/" + memberId)).body(new MemberRegisterResponseDto(memberId)).getBody()` 

##### 2번
`new MemberRegisterResponseDto(memberId))` 

코드 중복을 피하기 위해 To-Be 형태로 수정하면 좋을 것 같습니다.

##### As-Is
`return new ResponseEntity<>(
            ApiUtils.success(ResponseEntity.created(URI.create("/members/" + memberId))
                .body(new MemberRegisterResponseDto(memberId))
                .getBody()
            ),
            HttpStatus.CREATED
        );`

##### To-Be
`return ResponseEntity.created(URI.create("/members/" + memberId))
                .body(ApiUtils.success(new MemberRegisterResponseDto(memberId))));`

**Comment by kangyunsik** [comment]
그러네요.. KS-34 생성해서 PR 만들겠습니다.
저런 부분이 더 있다면, 추가 처리 하겠습니다~

[KS-34](https://kreamish.atlassian.net/jira/software/projects/KS/boards/4?selectedIssue=KS-34)

[KS-34]: https://kreamish.atlassian.net/browse/KS-34?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
